// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt_NET.Models.System;

#nullable disable

namespace Projekt_NET.Migrations
{
    [DbContext(typeof(DroneDbContext))]
    [Migration("20250531205350_Last2")]
    partial class Last2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projekt_NET.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Projekt_NET.Models.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<int>("FlightPathId")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("DeliveryId");

                    b.HasIndex("FlightPathId");

                    b.HasIndex("PackageId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("Projekt_NET.Models.DeliveryLog", b =>
                {
                    b.Property<int>("DeliveryLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryLogId"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeliveryLogId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("Deliverylogs");
                });

            modelBuilder.Entity("Projekt_NET.Models.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistrictId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Projekt_NET.Models.Drone", b =>
                {
                    b.Property<int>("DroneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DroneId"));

                    b.Property<DateTime>("AqDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CallSign")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DroneCloudId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("DroneId");

                    b.HasIndex("DroneCloudId");

                    b.HasIndex("ModelId");

                    b.ToTable("Drones");
                });

            modelBuilder.Entity("Projekt_NET.Models.DroneCloud", b =>
                {
                    b.Property<int>("DroneCloudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DroneCloudId"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DroneCloudId");

                    b.HasIndex("DistrictId");

                    b.ToTable("DroneClouds");
                });

            modelBuilder.Entity("Projekt_NET.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<DateTime?>("ArrivDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DroneId")
                        .HasColumnType("int");

                    b.Property<int?>("FlightPathId")
                        .HasColumnType("int");

                    b.Property<int>("Steps")
                        .HasColumnType("int");

                    b.HasKey("FlightId");

                    b.HasIndex("DroneId");

                    b.HasIndex("FlightPathId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("Projekt_NET.Models.FlightPath", b =>
                {
                    b.Property<int>("FlightPathId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightPathId"));

                    b.HasKey("FlightPathId");

                    b.ToTable("FlightPaths");
                });

            modelBuilder.Entity("Projekt_NET.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelId"));

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialGear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModelId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("Projekt_NET.Models.Operator", b =>
                {
                    b.Property<int>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperatorId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("DroneId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OperatorId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("Projekt_NET.Models.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("DroneId")
                        .HasColumnType("int");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("PackageId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DroneId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("Projekt_NET.Models.Delivery", b =>
                {
                    b.HasOne("Projekt_NET.Models.FlightPath", "FlightPath")
                        .WithMany()
                        .HasForeignKey("FlightPathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt_NET.Models.Package", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightPath");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Projekt_NET.Models.DeliveryLog", b =>
                {
                    b.HasOne("Projekt_NET.Models.Delivery", "Delivery")
                        .WithMany()
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("Projekt_NET.Models.District", b =>
                {
                    b.OwnsMany("Projekt_NET.Models.Coordinate", "BoundingPoints", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("DistrictId")
                                .HasColumnType("int");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("Id");

                            b1.HasIndex("DistrictId");

                            b1.ToTable("Districts_BoundingPoints");

                            b1.WithOwner()
                                .HasForeignKey("DistrictId");
                        });

                    b.Navigation("BoundingPoints");
                });

            modelBuilder.Entity("Projekt_NET.Models.Drone", b =>
                {
                    b.HasOne("Projekt_NET.Models.DroneCloud", "DroneCloud")
                        .WithMany()
                        .HasForeignKey("DroneCloudId");

                    b.HasOne("Projekt_NET.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Projekt_NET.Models.Coordinate", "Coordinate", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("Id");

                            b1.ToTable("Drones");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("Coordinate")
                        .IsRequired();

                    b.Navigation("DroneCloud");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Projekt_NET.Models.DroneCloud", b =>
                {
                    b.HasOne("Projekt_NET.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Projekt_NET.Models.Flight", b =>
                {
                    b.HasOne("Projekt_NET.Models.Drone", "Drone")
                        .WithMany()
                        .HasForeignKey("DroneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Projekt_NET.Models.FlightPath", "FlightPath")
                        .WithMany("FlightList")
                        .HasForeignKey("FlightPathId");

                    b.OwnsOne("Projekt_NET.Models.Coordinate", "DeliveryCoordinates", b1 =>
                        {
                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("Id");

                            b1.ToTable("Flights");

                            b1.WithOwner()
                                .HasForeignKey("Id");
                        });

                    b.Navigation("DeliveryCoordinates")
                        .IsRequired();

                    b.Navigation("Drone");

                    b.Navigation("FlightPath");
                });

            modelBuilder.Entity("Projekt_NET.Models.Package", b =>
                {
                    b.HasOne("Projekt_NET.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projekt_NET.Models.Drone", "Drone")
                        .WithMany()
                        .HasForeignKey("DroneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Drone");
                });

            modelBuilder.Entity("Projekt_NET.Models.FlightPath", b =>
                {
                    b.Navigation("FlightList");
                });
#pragma warning restore 612, 618
        }
    }
}
